import Head from 'next/head'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { useQuery } from '@apollo/client'
import { GET_POKEMONS } from '../graphQL/queries'

export default function Home() {
  const { error, loading, data } = useQuery(GET_POKEMONS)
  const [pokemonData, setPokemonData] = useState([])

  useEffect(() => {
    if (data){
      setPokemonData(data.pokemons.results)
    }
  }, [data])

  if (loading) return <nav>Loading...</nav>

  else if (error) return <div>Oops something is wrong</div>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {pokemonData.map((val) => (<div key={val.id}>{val.name}</div>))}
      </main>
    </div>
  )
}
